# Configuration for llm as a judge evaluation

# Model configuration
"model_id": "Qwen/Qwen3-32B"
"n_devices": 1
"max_model_len": 10000
"max_new_tokens": 500
"temperature": 0.7
"top_p": 0.8
"top_k": 20

cache_dir: /projectnb/vkolagrp/skowshik/.cache/

n_runs: 5

model: gemma_7B_instruct

n:
  # - 11
  - 14

values:
  - pos
  - neg

# type: sensitivity
type: layer_steering


# layer_steering

# data_path: "../../data/steer_results/layer_steering/llama31_8B_instruct_coeff_5_pos_steer.csv"
# save_name: "llm_as_a_judge_results/layer_steering/llama31_8B_instruct_coeff_5/pos/"

# data_path: "../../data/steer_results/layer_steering/llama31_8B_instruct_coeff_5_neg_steer.csv"
# save_name: "llm_as_a_judge_results/layer_steering/llama31_8B_instruct_coeff_5/neg/"

# data_path: "../interp/steer_results/layer_steering/llama31_8B_coeff_5_pos_steer.csv"
# save_name: "llm_as_a_judge_results/layer_steering/llama31_8B_coeff_5/pos/"

# data_path: "../interp/steer_results/layer_steering/llama31_8B_coeff_5_neg_steer.csv"
# save_name: "llm_as_a_judge_results/layer_steering/llama31_8B_coeff_5/neg/"

# data_path: "../../data/steer_results/layer_steering/qwen25_7B_instruct_coeff_5_pos_steer.csv"
# save_name: "llm_as_a_judge_results/layer_steering/qwen25_7B_instruct_coeff_5/pos/"

# data_path: "../../data/steer_results/layer_steering/qwen25_7B_instruct_coeff_5_neg_steer.csv"
# save_name: "llm_as_a_judge_results/qwen25_7B_instruct_coeff_5/neg/"

# data_path: "../interp/steer_results/layer_steering/gemma_7B_instruct_coeff_9_pos_steer.csv"
# save_name: "llm_as_a_judge_results/layer_steering/gemma_7B_instruct_coeff_9/pos/"

# data_path: "../interp/steer_results/layer_steering/gemma_7B_instruct_coeff_9_neg_steer.csv"
# save_name: "llm_as_a_judge_results/layer_steering/gemma_7B_instruct_coeff_9/neg/"

# Coefficient sensitivity

# data_path: "../interp/steer_results/sensitivity/llama31_8B_instruct_layer_12_pos_steer.csv"
# save_name: "llm_as_a_judge_results/sensitivity/llama31_8B_instruct_layer_12/pos/"

# data_path: "../interp/steer_results/sensitivity/llama31_8B_instruct_layer_12_neg_steer.csv"
# save_name: "llm_as_a_judge_results/sensitivity/llama31_8B_instruct_layer_12/neg/"

# data_path: "../interp/steer_results/sensitivity/qwen25_7B_instruct_layer_10_pos_steer.csv"
# save_name: "llm_as_a_judge_results/sensitivity/qwen25_7B_instruct_layer_10/pos/"

# data_path: "../interp/steer_results/sensitivity/qwen25_7B_instruct_layer_10_neg_steer.csv"
# save_name: "llm_as_a_judge_results/sensitivity/qwen25_7B_instruct_layer_10/neg/"

# data_path: "../interp/steer_results/sensitivity/gemma_7B_instruct_layer_12_pos_steer.csv"
# save_name: "llm_as_a_judge_results/sensitivity/gemma_7B_instruct_layer_12/pos/"

# data_path: "../interp/steer_results/sensitivity/gemma_7B_instruct_layer_12_neg_steer.csv"
# save_name: "llm_as_a_judge_results/sensitivity/gemma_7B_instruct_layer_12/neg/"


